export const SERVER_WALLET_ID = process.env.SERVER_WALLET_ID || 'varatharaj.testnet';
export const NEXT_PUBLIC_NETWORK = process.env.NEXT_PUBLIC_NETWORK || 'testnet';
export const ART_BATTLE_CONTRACT = process.env.ART_BATTLE_CONTRACT || 'artbattle.mintspace2.testnet';
export const ART_BATTLE_PROXY_CONTRACT = process.env.ART_BATTLE_PROXY_CONTRACT || '0.drop.proxy.mintbase.testnet';
export const SPECIAL_WINNER_CONTRACT = process.env.SPECIAL_WINNER_CONTRACT || "mygrayscale.mintspace2.testnet";
export const SERVER_WALLET_PK = process.env.SERVER_WALLET_PK || 'anon';
export const BASE_URL = process.env.BASE_URL || 'http://localhost:3000';
export const MONGODB_URI = process.env.MONGODB_URI || "mongodb://localhost:27017/"
export const OPENAI = process.env.OPENAI || ""
export const ACCOUNT_NAME = process.env.ACCOUNT_NAME || ""
export const ACCOUNT_KEY = process.env.ACCOUNT_KEY || ""
export const CONTAINER_NAME = process.env.CONTAINER_NAME || ""
export const GFX_CAMPAIGNID = process.env.NEXT_PUBLIC_GFX_CAMPAIGNID||"gfxvs"
export const ADMIN_ADDRESS = process.env.NEXT_PUBLIC_ADMIN_ADDRESS || ""
export const ADMIN_GMAIL = process.env.ADMIN_GMAIL || "sathish@kalakendradao.org"
export const ADMIN_PASS = process.env.ADMIN_PASS || ""
export const NEXT_PUBLIC_VALID_CLIENT_ID = process.env.NEXT_PUBLIC_VALID_CLIENT_ID || ""
export const NEXT_PUBLIC_VALID_CLIENT_SECRET = process.env.NEXT_PUBLIC_VALID_CLIENT_SECRET || ""
export const NEXT_PUBLIC_PROXY_ADDRESS = process.env.NEXT_PUBLIC_PROXY_ADDRESS||""